# SplitRename.spec
# PyInstaller build specification
# Run with: pyinstaller SplitRename.spec

import sys
from PyInstaller.building.build_main import Analysis, PYZ, EXE, COLLECT

block_cipher = None

a = Analysis(
    ['episode_splitter.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('ffmpeg_manager.py',  '.'),       # FFmpeg manager
        ('episode_namer.py',   '.'),       # TMDB/TVDB naming logic
        ('naming_dialog.py',   '.'),       # episode naming dialog
        ('assets/icon.ico',    'assets'),  # app icon
    ],
    hiddenimports=[
        'PyQt6.QtWidgets',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.sip',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib', 'numpy', 'pandas', 'scipy',
        'cv2', 'tkinter', 'wx',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,      # use COLLECT (folder mode, not onefile)
    name='SplitRename',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,              # no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets\\icon.ico',    # generated by build.bat if not present
    version='version_info.txt',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SplitRename',        # output folder: dist\SplitRename\
)
